version: '3.3'

services:
  db_postgres:
    container_name: db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2004

  profile-app:
    container_name: profile-app
    image: profile-app
    ports:
      - "8080:8080"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_postgres
    tty: true
    stdin_open: true
