spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 2004
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog.yaml
    drop-first: false
    database-change-log-table: change_log
    database-change-log-lock-table: change_log_lock